#====>CONFIG DRIVER
webdriver.driver=chrome
webdriver.autodownload=true
##webdriver.chrome.driver=C:\\driversSerenity\\chromedriver-win64\\chromedriver.exe
serenity.browser.maximized=true
headless.mode=false
# espera implicita de elementos en acciones, default= 5seg | igual que webdriver.timeouts.fluentwait
webdriver.wait.for.timeout=8000
# tiempo de espera cuando se usa WaitUntil.
webdriver.timeouts.implicitlywait=16000
# pausa en milisegundos entre cada step
#serenity.step.delay=0
#Para ejecucion movil esta propiedad permite que un conjunto de escenarios se ejecute en un mismo dispositivo en Browserstack. Acepta las siguientes opciones: feature | never | scenario | story |
#serenity.restart.browser.for.each = never

#====>CONFIG MANUAL TEST
current.target.version=sprint-1
report.assets.directory=${user.dir}/src/test/resources/assets


#====>CONFIG REPORTS
serenity.project.name=Automation Arq. SerenityBDD
serenity.summary.report.title=Automation Arq. SerenityBDD
#acepta las siguientes opciones: FOR_EACH_ACTION | BEFORE_AND_AFTER_EACH_STEP | AFTER_EACH_STEP | FOR_FAILURES | DISABLED
#serenity.take.screenshots=FOR_FAILURES
serenity.tag.failures=true
report.customfields.applicationName=Examples Automation
report.customfields.cell=Equipo Transversal de Automatizacion
report.customfields.automator=EquipoE2E
report.customfields.orders=applicationName, cell, automator


#====>CONFIG ADDITIONAL
#- NONE: deshabilitar el registro de Serenity | QUIET: Solo reporta pruebas comprometidas, errores y fallas. | - NORMAL: Registra el inicio y final de cada prueba, y el resultado de cada prueba. | - VERBOSE: registra el inicio y el final de cada prueba, el resultado de cada prueba y cada paso de la prueba.
serenity.logging=VERBOSE
serenity.console.colors=true


#====>CONFIG OPTIONAL
#Si no se agregan, tomara por defecto "src/test/resources", "src/test/resources/features/", "src/test/resources/data/" y "src/test/resources/properties/" respectivamente
#path.resources=
#path.features=
#path.data=
#path.properties=


#=====> ATRIBUTOS PARA USAR DRIVER PERSONALIZADO
#webdriver.driver=provided
#webdriver.provided.type=mydriver
#webdriver.provided.mydriver=com.pichincha.automationtest.util.execution.CustomDriver
#serenity.driver.capabilities=mydriver
#project.driver=edge


#====>CONFIG MOBILE TEST BROWSERSTACK PIPELINE
#appium.hub=https://${APPIUM_BROWSERSTACK_USER}:${APPIUM_BROWSERSTACK_KEY}@hub-cloud.browserstack.com/wd/hub
#appium.platformName=${APPIUM_PLATFORM_NAME}
#appium.deviceName=${APPIUM_DEVICE_NAME}
#appium.platformVersion=${APPIUM_PLATFORM_VERSION}
#appium.app=${APPIUM_APP}


#====>CONFIG MOBILE TEST BROWSERSTACK DIRECTO

#appium.platformName=Android
#appium.deviceName=Samsung Galaxy S22 Ultra
#appium.platformVersion=12.0
#appium.app=bs://34cb9199e3b52eb011a354c6ec7b2aaf8e4ba252


#====>CONFIG MOBILE TEST LOCAL
#appium.hub=http://127.0.0.1:4723/
#appium.udid=emulator-5554
#appium.platformName=Android
#appium.deviceName=PixelJoEs
#appium.platformVersion=15.0
#appium.automationName=UiAutomator2
#appium.app=${user.dir}/src/test/resources/Calc.apk
################################para que funcione en iOS deben estar estos tambien
#appium.automationName=XCUITest
#appium.deviceName=Iphone 12 JoEs
#appium.platformVersion=16.0


#====>CONFIG MOBILE TEST GENERAL
#Si noReset esta en true NO va a borrar los datos del aplicativo en cada ejecucion del escenario caso contrario va a borrar los datos de la aplicacion
#appium.noReset=true
#appium.newCommandTimeout = 1000
#appium.groupId=
#appium.bundleId=
#appium.username=
#appium.accessKey=
#Listar apps subidas en BrowserStack
#https://www.browserstack.com/docs/app-automate/api-reference/appium/apps
#Listar disponibles dispositivos para ejecuciones en browserstak
#https://www.browserstack.com/list-of-browsers-and-platforms-page/app_automate